### ISSUE TITLE
Push documentation for currently (May 2019) unsupported SDKs

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#298] opened 2017-06-11 19:22 UTC
Issue to keep track of outstanding docs for https://github.com/ably/docs/pull/257:

* [x] Python REST docs
* [x] PHP REST docs
* [ ] .NET REST docs (when supported)
* [ ] .NET Realtime docs (when supported)
* [ ] Go REST docs (when supported)

**Comment by tcard** [comment] 2017-08-25 10:38
I'll add some feedback from a customer here about the interaction between Apple's API and Ably's, specially about the purpose of `push.activate`. I agree it's far from clear currently.

<details>
but when I call client.push.activate()...I don't get any callback success or fail
The documentation isn't up to scratch btw...

------

Hi! So you have a didActivateAblyPush: method on your UIApplication but it isn't being called?

------

it's in my UIApplicationDelegate
but yes it isn't being called. The other way which is registering via Apple regular method, then calling Ably didRegister method makes it work, I can publish notifications and they device catch them...but I thought it's probably better to do it fully via Ably, not half way 😀

------

Sorry, yes, that's what I meant.

------

But you have to do both. You need to hook Apple's didRegister... with Ably's. Then Ably will save your device token, and then it's supposed to call the didActivateAblyPush method.

------

Oh OK, I might have misunderstood the documentation
so does that mean that when this is called :

didRegisterForRemoteNotificationsWithDeviceToken
I have to call ARTPush.didRegisterForRemoteNotifications(withDeviceToken: deviceToken, realtime: client)
when do I call activate() in the process, I don't get that

------

That's right.
You can call activate() at any point you want, e. g. it might be as a result of a user action, but typically you do it at start up.

------

But you do it after the regular registration has been done, correct ?
( at the moment, it works for me, I just want to make sure I'm doing stuff correctly )

------

The registration with Apple, you mean? Yes, but you don't have to worry about it. activate()  just starts off the process of registering with Ably, and that process will wait for Apple's device token if it's missing, or use it if it has it already.

------

You just need to do the bridging between Apple and Ably, by calling ARTPush.didRegisterForRemoteNotifications... . Ably can't do it by itself since the didRegisterForRemoteNotificationsWithDeviceToken method must be in your UIApplicationDelegate and that's under your control.

------

Yeah I get that. I'm just curious on what's the purpose of activate*( then
because I do as you explained, I don't call activate and I still receive real time push notifications and proper notifications on the device...so I'm a bit lost on what's activate for

------

Giving you control over when do you want to start that process.
That's probably because you called activate()   on an earlier execution. The effects of activate()  outlive the current execution of the app.

------

ok, lol then I understood correctly what activate() is for.
Instead of calling

let setting:UIUserNotificationSettings = UIUserNotificationSettings(types: [.alert, .badge, .sound], categories: nil)
UIApplication.shared.registerUserNotificationSettings(setting)
UIApplication.shared.registerForRemoteNotifications(),

You just call activate

------

No, again you have to do both. Because that's for Apple, but our activate()  is for Ably.

------

We'll probably have to change the documentation to make this clear.

------

Ok
I don't call activate() at all though...and it doesn't seem to be an issue whatsoever Haha

------

Do you mind if I just quote this conversation (will be in public)? Anonymously.

------

That's why I'm confused on the purpose of calling it
ah no, don't worry 😀
you can, if it can improve stuff, it's better for every one
the documentation needs an update on the PUsh Notication from server side too 😉

------

Yeah. The whole push thing is in beta, so it was put together kind of quickly and when things were still in flux. But we're focusing on stabilizing now.

------

I can confirm though that calling activate doesn't call any of the callback I have in my AppDelegate
it's no biggie since the notification is working any way
but in my mind, I think activate should be used to completely take over from Apple, so you call activate and it will call the didRegister or didFail in app delegate

------

OK, I'll look into that.

------

but that was probably not the way intended haha
and just me complaining 😉
</details>

**Comment by mattheworiordan** [comment] 2019-10-30 06:49
@tomczoink can you confirm this is no longer an issue?

**Comment by tomczoink** [comment] 2019-10-30 09:09
We still need Go documentation for Push, but as far as I'm aware that's not been implemented yet. @paddybyers if it has let me know and I can add docs for it as well.

**Comment by mattheworiordan** [comment] 2019-10-30 09:10
> but as far as I'm aware that's not been implemented yet.

Yup, not implemented, so not needed :)

Perhaps just raise an issue in Go to add push (if one doesn't exist) + add docs, and then we can close this.

**Comment by tomczoink** [comment] 2019-10-30 09:13
New issue at https://github.com/ably/ably-go/issues/126, closing this.

**Closed by tomczoink** 2019-10-30 09:13 UTC
Labels: api docs, enhancement, push
