### ISSUE TITLE
Revisit backoff strategy for client libraries

### ISSUE THREAD

**Issue by paddybyers** [ably/docs#832] opened 2020-03-05 11:56 UTC
Currently a library will retry a request, or attempt to reconnect, if it receives a 5xx error. The retry sequence is simply a periodic retry with a fixed interval, which causes a couple of issues:

- as there is no backoff, this can lead to a very high sustained rate of retries, if there is a large number of failing clients;

- since all clients implement the same backoff time, they can all retry simultaneously if the original failure occurred simultaneously (as has happened in some recent incidents).

A more intelligent retry approach, including some form of backoff and jitter, would address those problems.

Separately, a library will **not** retry if it receives a rate-limiting error with a 429 error code. However, many applications want to retry these operations, and so they perform retry within their own code. This can cause problems because, especially in the rate-limiting case, some backoff would be highly desirable. If the library implemented an intelligent retry on a 429 error, then we could minimise the degree to which applications use a less sympathetic retry strategy themselves.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/EDU-56) by [Unito](https://www.unito.io)

**Comment by mattheworiordan** [comment] 2020-03-05 19:17
This was not tagged correctly, please remember to add client lib spec for proposed changes

**Comment by QuintinWillison** [comment] 2021-10-01 18:45
Related to, perhaps a duplicate of, https://github.com/ably/docs/issues/676

**Comment by Morganamilo** [comment] 2022-05-06 08:21
i'm a little confused on what this solves. Retries are done via a list of fallback hosts, and when a fallback host works it's saved and used as the main host for a period of time. Fallback hosts are also tried in a random order which could be though of as jitter.  So it kind of seems to be that the issue trying to be addressed is already accounted for by alternative hosts.

(Assuming each host hits a separate datacenter but I don't know how it actually works)

For an intelligent retry on 429, does this mean reusing the existing retry logic where we try a different host, or do we try the same host again?

**Comment by paddybyers** [comment] 2022-05-11 17:21
The `disconnected` and `connecting` states anticipate imminent connection establishment - ie the library behaves in a way that anticipates connection. Published messages and other operations are queued, for enactment once the connection is established, and on reconnection the expectation is of a successful resume. This means that retries at a certain minimum frequency are required. We can't back off for 1 minute, say, if successive retried connections fail, and remain in the `disconnected` state. So I think that continuing when `disconnected` to retry at least approximately every 30s, (or maybe at least approximately every 15s), is necessary. This is until the 2 minute window expires, and then you revert to `suspended` state.

So in implementing this proposal I don't think it's appropriate to do a lot of backing off. We already make the first reconnection attempt immediately, and then subsequent attempts are on a 15s interval. I think we're going to continue to do roughly the same thing. Maybe we have a backoff sequence which is 15s, 20s, 25s, 30s. But I don't think it should increase from there.

I think we can definitely introduce jitter, and we want to avoid simultaneous reconnection attempts being made if there are large scale simultaneous disconnections. It doesn't have to be sophisticated - some uniform distribution around the target value.

**Comment by owenpearson** [comment] 2022-05-18 09:49
@paddybyers Would your 15 -> 30s backoff strategy also be appropriate for 429 errors? It seems like since jitter wouldn't be useful for 429s then the backoff sequence up to 30 seconds wouldn't be that much different than just constant 15s retries. I don't know why we don't retry 429s in the first place so I'm not sure how to judge what a good enough strategy for 429s would be.

**Comment by paddybyers** [comment] 2022-05-19 16:40
Currently we don't retry 429 responses in the libraries. There's only a small set of 4xx responses that we retry, and those are the ones relating to token errors - a request is validly retriable once a token has been renewed.

I do think there are situations where 429 should be retried, but it's not straightforward, and I think doing that is outside the scope of the present task. We're mainly being hit by:
- retried connection attempts following disconnection; and
- retried HTTP requests after a 5xx response

**Closed** 2022-06-09 09:59 UTC
Labels: content-request, client-lib-spec
